### ISSUE TITLE
Backup処理の修正

### ISSUE THREAD

**Issue by takokun778** [morning-night-guild/platform-app#133]
```shell
2023-04-07 18:01:14.93 UTCplatform-db-backup-28014840-58mlzplatform-db-backup2023/04/07 18:01:14 Tx(44f4cd63-ee68-42d6-9463-a83698a5e7ea).Exec: query=ALTER TABLE "articles" DROP CONSTRAINT "articles_pkey" , ADD PRIMARY KEY ("id") args=[]
2023-04-07 18:01:14.96 UTCplatform-db-backup-28014840-58mlzplatform-db-backup2023/04/07 18:01:14 Tx(44f4cd63-ee68-42d6-9463-a83698a5e7ea): rollbacked
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backup{"level":"panic","ts":1680890474.9712343,"caller":"backup/main.go:41","msg":"failed to create secondary schema","error":"sql/schema: modify \"articles\" table: pq: cannot drop constraint articles_pkey on table articles because other objects depend on it","stacktrace":"main.main\n\tgithub.com/morning-night-guild/platform-app/cmd/db/backup/main.go:41\nruntime.main\n\truntime/proc.go:250"}
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backuppanic: failed to create secondary schema
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backup
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backupgoroutine 1 [running]:
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backupgo.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0xaf7b2c?, {0x0?, 0x0?, 0xc00018d080?})
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backup go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backupgo.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00035c1a0, {0xc0001837c0, 0x1, 0x1})
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backup go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backupgo.uber.org/zap.(*Logger).Panic(0x0?, {0xb07d69?, 0x0?}, {0xc0001837c0, 0x1, 0x1})
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backup go.uber.org/zap@v1.24.0/logger.go:258 +0x59
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backupmain.main()
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backup github.com/morning-night-guild/platform-app/cmd/db/backup/main.go:41 +0x7ea
```

**Comment by Shitomo** [comment]
```
2023-04-07 18:01:14.93 UTCplatform-db-backup-28014840-58mlzplatform-db-backup2023/04/07 18:01:14 Tx(44f4cd63-ee68-42d6-9463-a83698a5e7ea).Exec: query=ALTER TABLE "articles" DROP CONSTRAINT "articles_pkey" , ADD PRIMARY KEY ("id") args=[]
2023-04-07 18:01:14.96 UTCplatform-db-backup-28014840-58mlzplatform-db-backup2023/04/07 18:01:14 Tx(44f4cd63-ee68-42d6-9463-a83698a5e7ea): rollbacked
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backup{"level":"panic","ts":1680890474.9712343,"caller":"backup/main.go:41","msg":"failed to create secondary schema","error":"sql/schema: modify \"articles\" table: pq: cannot drop constraint articles_pkey on table articles because other objects depend on it","stacktrace":"main.main\n\tgithub.com/morning-night-guild/platform-app/cmd/db/backup/main.go:41\nruntime.main\n\truntime/proc.go:250"}
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backuppanic: failed to create secondary schema
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backup
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backupgoroutine 1 [running]:
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backupgo.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0xaf7b2c?, {0x0?, 0x0?, 0xc00018d080?})
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backup go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backupgo.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00035c1a0, {0xc0001837c0, 0x1, 0x1})
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backup go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backupgo.uber.org/zap.(*Logger).Panic(0x0?, {0xb07d69?, 0x0?}, {0xc0001837c0, 0x1, 0x1})
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backup go.uber.org/zap@v1.24.0/logger.go:258 +0x59
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backupmain.main()
2023-04-07 18:01:14.97 UTCplatform-db-backup-28014840-58mlzplatform-db-backup github.com/morning-night-guild/platform-app/cmd/db/backup/main.go:41 +0x7ea
```
